version: "3.7"

services:
    database:
        image: postgres
        container_name: {CONTAINER_NAME}
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER={USER}
            - POSTGRES_PASSWORD={PASS}
            - POSTGRES_DB=rentalx
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentalx
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        # network_mode: host
        links: 
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local